### ISSUE TITLE
Support for lazy load component

### ISSUE THREAD

**Issue by Rasool-deldar** [fumeapp/nuxt-storm#2]
Hello, thank you for creating this package.
I wanted to say that this package has a problem that does not detect lazy load component, please fix this problem as well.

.components.gen.js

![image](https://user-images.githubusercontent.com/58503211/123591948-e0062c80-d801-11eb-8f35-8d5bac681322.png)

![image](https://user-images.githubusercontent.com/58503211/123591739-9ddceb00-d801-11eb-8b33-ccb75771e0f3.png)

**Comment by acidjazz** [comment]
@Rasool-deldar is the solution to pre-pend this with `Lazy` ? PR's are more than welcome!

**Comment by Rasool-deldar** [comment]
Yes, using Lazy, please click on the link below.

[lazy-loading-your-components](https://nuxtjs.org/blog/improve-your-developer-experience-with-nuxt-components#lazy-loading-your-components)
